version: '3'

services:
  app:
    container_name: django-app-container
    build: ./app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - dj_data:/djangoapp


  nginx:
    container_name: nginx-container
    build: ./nginx
    volumes:
      - ./log:/var/log/nginx
    ports:
      - '80:80'
    depends_on:
      - app

volumes:
  dj_data:
